device: 'cuda'
seed: 1
fold: 1
debug: False
log: False
data:
  name: 'kvasir-seg'
  train_folder: 'data_processed/kvasir-seg/'
  val_folder: 'data_processed/kvasir-seg/'
  test_folder: 'data_processed/kvasir-seg/'
  save_folder: 'checkpoints/kvasir-seg'
  supervised_ratio: 0.25
  train_aug: True
  img_size: 224

semi:
  conf_thresh: 0.95

train:
  l_batchsize: 8
  u_batchsize: 8
  num_workers: 0
  num_epochs: 80
  num_iters: False 
  ema_decay: 0.99
  optimizer:
    mode: 'adamw'
    adamw:
      lr: 1e-4
      betas: 
        - 0.9
        - 0.999
      eps: 1e-8
      weight_decay: 0.05
    adam:
      lr: 1e-4
      betas:
        - 0.9
        - 0.999

test:
  only_test: False  
  test_model_dir: ''
  num_workers: 0
  batch_size: 8



model_encoder_id: 0
model_adapt:
  adapt_method: False
  num_domains: 1
